# Other
export GIT_EDITOR=vim
export SVN_EDITOR=vim
export EDITOR=vim

# Bash
source $HOME/.bash_aliases
source $HOME/.bash_functions

# Colorize prompt and directories
eval $(dircolors -b $HOME/.dircolors)
promptcolors

# Show directory in urxvt title bar
case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
  ;;
    *)
  ;;
esac
