export GIT_EDITOR=vim
export SVN_EDITOR=vim
export EDITOR=vim

# Bash
export PATH=$HOME/bin:/sbin:$PATH
source $HOME/.bash_aliases
source $HOME/.bash_functions

# Setup keychain
if [ -e $HOME/.ssh/id_dsa ]; then
  keychain $HOME/.ssh/id_dsa
fi

if [ -e $HOME/.ssh/id_rsa ]; then
  keychain $HOME/.ssh/id_rsa
fi

source $HOME/.keychain/$HOSTNAME-sh

# Colorize prompt and directories
eval $(dircolors -b $HOME/.dircolors)
promptcolors

# Show directory in urxvt title bar
case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
  ;;
    *)
  ;;
esac
