# Java
export ANT_OPTS="-Xms512M -Xmx1024M -XX:MaxPermSize=1024M"
export ANT_ARGS='-logger org.apache.tools.ant.listener.AnsiColorLogger'
export JAVA_HOME=/opt/java
export JDK_HOME=$JAVA_HOME
export _JAVA_OPTION=

# Haskell
export GHCRTS="-K512M"

# Other
export GIT_EDITOR=vim
export SVN_EDITOR=vim
export EDITOR=vim
export MAILCHECK=NO

# Bash
export HISTCONTROL=erasedups:ignorespace
export HISTIGNORE="ls:pwd:exit:mount:rm:screen:vi:cd"
unset HISTSIZE
unset HISTFILESIZE
shopt -s histappend
source $HOME/.bash_functions
source $HOME/.bash_aliases
if [ -e $HOME/.bash_local ]; then
  source $HOME/.bash_local
fi
addpath $JAVA_HOME/bin
addpath $HOME/.gem/ruby/2.0.0/bin
addpath $HOME/bin

# Setup keychain
if [ -e $HOME/.ssh/id_dsa ]; then
  keychain --quiet $HOME/.ssh/id_dsa
fi
if [ -e $HOME/.ssh/id_rsa ]; then
  keychain --quiet $HOME/.ssh/id_rsa
fi
if [ -e $HOME/.leiningen/id_rsa ]; then
  keychain --quiet $HOME/.leiningen/id_rsa
fi
source $HOME/.keychain/$HOSTNAME-sh

# Colorize prompt and directories
eval $(dircolors -b $HOME/.dircolors)
promptcolors

# Hostname and path appears in terminal title
case "$TERM" in
  xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD}\007"'
  ;;
    *)
  ;;
esac
