# Set keyboard delay/rate.
xset r rate 275 30

# Turn off the beep.
xset -b

# Swap capslock and control.
setxkbmap -option ctrl:swapcaps

# Turn off the damned touchpad.
synclient TouchpadOff=1

# Set mouse acceleration.
#
# See: https://wiki.archlinux.org/index.php/Mouse_acceleration
xset m 2

# Enable vertical scrolling for trackpoint
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation' 8 1
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Button' 8 2
#xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Timeout' 8 200

# Enable horizontal scrolling for trackpoint
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Axes' 8 6 7 4 5

# Enable IBus for Chinese input.
#
# See: https://wiki.archlinux.org/index.php/IBus
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULE=ibus
#GTK2_RC_FILES=/home/minhuang/.ibus-gtkrc-2.0 ibus-daemon --xim -d

# Desktop applications have two selections: PRIMARY and CLIPBOARD.
# PRIMARY: text selected with the mouse and pasted with middle click.
# CLIPBOARD: text selected via Edit -> Copy and pasted with Paste from the menu.
# The following two lines will keep both in sync with each other.
#
# See: http://www.nongnu.org/autocutsel/
autocutsel -fork -selection PRIMARY -buttonup &
autocutsel -fork -selection CLIPBOARD -buttonup &

# If using .xinitrc, this file will not be read by default, so read merge
# it here.
#
# See: https://wiki.archlinux.org/index.php/X_resources
xrdb -merge ~/.Xresources

# Enable the screensaver.
xscreensaver -nosplash &

# Make looking at the screen at night easier on the eyes.
/usr/bin/redshift -o -l 0:0 -b 0.8 -t 6500:6500

# Prepending exec is recommended as it replaces the current process with the
# process, so the script will stop running and X won't exit even if the process
# forks into the background.
#
# See: https://wiki.archlinux.org/index.php/Xinitrc
exec dbus-launch /usr/bin/i3
