# Set keyboard delay/rate
xset r rate 275 30
# Swap capslock and control
setxkbmap -option ctrl:swapcaps

# Turn off the damned touchpad
synclient TouchpadOff=1
# Set mouse acceleration
xset m 2

xscreensaver -nosplash &
tpb -d
eval `ssh-agent`

while true; do
  wmii
  xmessage 'Do you want to restart wmii?' \
           -buttons 'Yes:1,No:0' \
           -center \
           -default 'Yes' \
           -timeout 30 \
  && break
done
