# Set keyboard delay/rate
xset r rate 275 30

# Turn off the beep
xset -b

# Swap capslock and control
setxkbmap -option ctrl:swapcaps

# Turn off the damned touchpad
synclient TouchpadOff=1

# Set mouse acceleration
xset m 2

# Enable vertical scrolling for trackpoint
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation' 8 1
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Button' 8 2
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Timeout' 8 200

# Enable horizontal scrolling for trackpoint
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Axes' 8 6 7 4 5

# Enable IBus for Chinese input
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
GTK2_RC_FILES=/home/minhuang/.ibus-gtkrc-2.0 ibus-daemon --xim -d

# Start Thinkpad OSD daemon
if [ -x /usr/bin/tpb ] &&  [ -w /dev/nvram ] && [ -r /dev/nvram ]; then
  /usr/bin/tpb -d
fi

urxvtd -q -o -f
xscreensaver -nosplash &
ssh-agent | sed -e '3d' > ~/.ssh/agent

exec /usr/bin/i3
